config/routes.rb
Rails.application.routes.draw do
  resources :ideaposts
  resources :users
  root 'users#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/ideapost.rb
class Ideapost < ApplicationRecord
    belongs_to :user
    validates :content, presence: true
end

app/models/user.rb
class User < ActiveRecord::Base
    has_many :ideaposts
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  def hello
    render html: "hello, world"
  end
end

app/controllers/ideaposts_controller.rb
class IdeapostsController < ApplicationController
  before_action :set_ideapost, only: [:show, :edit, :update, :destroy]

  # GET /ideaposts
  # GET /ideaposts.json
  def index
    @ideaposts = Ideapost.all
  end

  # GET /ideaposts/1
  # GET /ideaposts/1.json
  def show
  end

  # GET /ideaposts/new
  def new
    @ideapost = Ideapost.new
  end

  # GET /ideaposts/1/edit
  def edit
  end

  # POST /ideaposts
  # POST /ideaposts.json
  def create
    @ideapost = Ideapost.new(ideapost_params)

    respond_to do |format|
      if @ideapost.save
        format.html { redirect_to @ideapost, notice: 'Ideapost was successfully created.' }
        format.json { render :show, status: :created, location: @ideapost }
      else
        format.html { render :new }
        format.json { render json: @ideapost.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /ideaposts/1
  # PATCH/PUT /ideaposts/1.json
  def update
    respond_to do |format|
      if @ideapost.update(ideapost_params)
        format.html { redirect_to @ideapost, notice: 'Ideapost was successfully updated.' }
        format.json { render :show, status: :ok, location: @ideapost }
      else
        format.html { render :edit }
        format.json { render json: @ideapost.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /ideaposts/1
  # DELETE /ideaposts/1.json
  def destroy
    @ideapost.destroy
    respond_to do |format|
      format.html { redirect_to ideaposts_url, notice: 'Ideapost was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_ideapost
      @ideapost = Ideapost.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def ideapost_params
      params.require(:ideapost).permit(:content, :user_id)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:specialname)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/ideaposts_helper.rb
module IdeapostsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/ideaposts/_form.html.erb
<%= form_for(ideapost) do |f| %>
  <% if ideapost.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(ideapost.errors.count, "error") %> prohibited this ideapost from being saved:</h2>

      <ul>
      <% ideapost.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :content %>
    <%= f.text_area :content %>
  </div>

  <div class="field">
    <%= f.label :user_id %>
    <%= f.number_field :user_id %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/ideaposts/edit.html.erb
<h1>Editing Ideapost</h1>

<%= render 'form', ideapost: @ideapost %>

<%= link_to 'Show', @ideapost %> |
<%= link_to 'Back', ideaposts_path %>

app/views/ideaposts/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Ideaposts</h1>

<table>
  <thead>
    <tr>
      <th>Content</th>
      <th>User</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @ideaposts.each do |ideapost| %>
      <tr>
        <td><%= ideapost.content %></td>
        <td><%= ideapost.user_id %></td>
        <td><%= link_to 'Show', ideapost %></td>
        <td><%= link_to 'Edit', edit_ideapost_path(ideapost) %></td>
        <td><%= link_to 'Destroy', ideapost, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Ideapost', new_ideapost_path %>

app/views/ideaposts/new.html.erb
<h1>New Ideapost</h1>

<%= render 'form', ideapost: @ideapost %>

<%= link_to 'Back', ideaposts_path %>

app/views/ideaposts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Content:</strong>
  <%= @ideapost.content %>
</p>

<p>
  <strong>User:</strong>
  <%= @ideapost.user_id %>
</p>

<%= link_to 'Edit', edit_ideapost_path(@ideapost) %> |
<%= link_to 'Back', ideaposts_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Workspace</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :specialname %><br>
    <%= f.text_field :specialname %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form' %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Users</h1>

<table>
  <thead>
    <tr>
      <th>Specialname</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.specialname %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<h1>New User</h1>

<%= render 'form' %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Specialname:</strong>
  <%= @user.specialname %>
</p>

<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>